include delphi.inc
include ../compiler.inc

all: aplasvr.exe

clean: clean-prog

clean-prog:
	rm -f aplasvr.exe aplasvr.log

aplasvr.exe: aplasvr.dpr aplasvr.mo

aplasvr.mo: aplasvr.po



