include delphi.inc
include ../compiler.inc

all: test-auto.exe tests.exe
	test-auto.exe

clean: clean-prog

clean-prog:
	rm -f test-auto.exe tests.exe

test-auto.exe: test-auto.dpr

tests.exe: tests.dpr

